[package]
name = "playground"
version = "0.1.0"
authors = ["Eva Wong <suddenlyeva@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = { path = "../tetra" }
shipyard = "0.4"
rand = "0.7.3"